apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - image: docker:20.10.12-dind
    name: debug
    command: ["sleep", "3600"]
    env:
      - name: DOCKER_TLS_VERIFY
        value: ""
      - name: DOCKER_HOST
        value: tcp://dinp-deployment:2375
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
